name: Enhancement Request
description: I want to request a feature or suggest an enhancement for Akcio
title: "[Enhancement]:"
labels: [enhancement]
assignees:
- jaelgu
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to request/suggest an enhancement for Akcio! Please fill the form in English!
- type: textarea
  attributes:
    label: What would you like to be added?
    description: A concise description of what you're expecting/suggesting.
    placeholder: |
      I would like to suggest/request a feature that's like...
  validations:
    required: false
- type: textarea
  attributes:
    label: Why is this needed?
    description: A concise description of the reason/motivation
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about this!
  validations:
    required: false